declare module 'react-native-ico-font-awesome' {
    import { ReactNode } from 'react';
    import { SvgProps } from 'react-native-svg';

    type AdditionalProps = {
      onError?: (error: Error) => void;
      onLoad?: () => void;
      fallback?: ReactNode;
    };

    type iconNames = 'bitcoin-logo' |
      'arrow-up-on-a-black-circle-background' |
      'stack-exchange-symbol' |
      'ban-circle-symbol' |
      'sign-out-option' |
      'align-justify' |
      'telephone-symbol-button' |
      'sign-in' |
      'arrow-pointing-to-right' |
      'folder-closed-black-shape' |
      'numbered-list' |
      'gift-box' |
      'quote-left' |
      'long-arrow-pointing-up' |
      'windows-logo-silhouette' |
      'left-arrow' |
      'man' |
      'double-angle-pointing-to-right' |
      'fighter-jet-silhouette' |
      'reply-arrow' |
      'thumbs-up' |
      'delivery-truck-silhouette' |
      'pause-symbol' |
      'volume-off' |
      'film-strip-with-two-photograms' |
      'long-arrow-pointing-to-left' |
      'bitbucket-sign' |
      'step-forward' |
      'stethoscope' |
      'zoom-out' |
      'beer-jar-black-silhouette' |
      'cog-wheel-silhouette' |
      'coffee-cup-on-a-plate-black-silhouettes' |
      'smile' |
      'folder-white-shape' |
      'chevron-up' |
      'anchor-shape' |
      'open-padlock-silhouette' |
      'dollar-symbol' |
      'exclamation-sign' |
      'spinner-of-dots' |
      'ticket' |
      'arrow-angle-pointing-down' |
      'google-plus-symbol-1' |
      'pinterest-sign' |
      'book' |
      'chevron-arrow-up' |
      'trophy' |
      'hostpital-building' |
      'arrow-pointing-to-left' |
      'play-video-button' |
      'beaker' |
      'correct-symbol' |
      'female-silhouette' |
      'github-character' |
      'circle-with-an-arrow-pointing-to-left' |
      'small-rocket-ship-silhouette' |
      'sun' |
      'renren-social-network-of-china-logotype' |
      'maxcdn-website-logo' |
      'square-shape-shadow' |
      'padlock' |
      'question-mark-on-a-circular-black-background' |
      'horizontal-resize-option' |
      'share-symbol' |
      'star' |
      'external-link-square-with-an-arrow-in-right-diagonal' |
      'trello-website-logo' |
      'trash' |
      'angle-arrow-pointing-to-right' |
      'great-britain-pound' |
      'right-quotation-mark' |
      'plus-sign-in-a-black-circle' |
      'bookmark-white' |
      'map-marker' |
      'bitbucket-logotype-camera-lens-in-perspective' |
      'resize-option' |
      'meh-face-emoticon' |
      'check-mark' |
      'thumb-down' |
      'arrowhead-pointing-to-the-right' |
      'sort-by-alphabet' |
      'checkered-raised-flag' |
      'volume-up-interface-symbol' |
      'envelope' |
      'check-box-empty' |
      'eye-with-a-diagonal-line-interface-symbol-for-invisibility' |
      'xing-logotype' |
      'compass-circular-variant' |
      'nine-black-tiles' |
      'envelope-of-white-paper' |
      'vimeo-square-logo' |
      'comment-white-oval-bubble' |
      'right-chevron' |
      'credit-card' |
      'rupee-indian' |
      'u-shaped-thick-magnet' |
      'file' |
      'ambulance' |
      'medical-kit' |
      'fullscreen-symbol' |
      'camera-retro' |
      'gittip-website-logo' |
      'twitter-sign' |
      'double-sided-eraser' |
      'circular-shape-silhouette' |
      'check' |
      'dashboard' |
      'tumblr-logo-1' |
      'sort-arrows-couple-pointing-up-and-down' |
      'photo-camera' |
      'linkedin-letters' |
      'sitemap' |
      'wheelchair' |
      'dot-and-circle' |
      'cloud-storage-download' |
      'plant-leaf-with-white-details' |
      'open-wrench-tool-silhouette' |
      'legal-hammer' |
      'rss-feed-button' |
      'finger-of-a-hand-pointing-to-right-direction' |
      'xing-logo' |
      'video-play-square-button' |
      'remove-symbol' |
      'code-fork-symbol' |
      'bar-graph-on-a-rectangle' |
      'checked-symbol' |
      'linkedin-sign' |
      'gamepad-console' |
      'reorder-option' |
      'question-sign' |
      'arrow-pointing-down' |
      'text-file' |
      'archive-black-box' |
      'shield' |
      'forward-button' |
      'star-1' |
      'microphone-black-shape' |
      'level-up' |
      'text-width' |
      'tint-drop' |
      'settings' |
      'suitcase-with-white-details' |
      'double-strikethrough-option' |
      'fire-symbol' |
      'up-chevron-button' |
      'upload-button' |
      'text-file-1' |
      'desktop-monitor' |
      'minus-sign-inside-a-black-circle' |
      'font-selection-editor' |
      'stack-exchange-logo' |
      'vertical-ellipsis' |
      'shopping-cart-black-shape' |
      'instagram-symbol' |
      'open-folder-outline' |
      'save-file-option' |
      'hand-finger-pointing-down' |
      'plus-symbol-in-a-rounded-black-square' |
      'briefcase' |
      'double-left-chevron' |
      'chevron-arrow-down' |
      'left-indentation-option' |
      'vintage-key-outline' |
      'cut' |
      'pencil' |
      'fork-and-knife-silhouette' |
      'sort-by-attributes-interface-button-option' |
      'arrowhead-pointing-up-inside-a-square-box-outline' |
      'cocktail-glass' |
      'picture' |
      'comment-black-oval-bubble-shape' |
      'three-small-square-shapes' |
      'sort-down' |
      'align-to-right' |
      'exclamation' |
      'qr-code' |
      'undo-arrow' |
      'hotel-letter-h-sign-inside-a-black-rounded-square' |
      'sort-reverse-alphabetical-order' |
      'couple-of-arrows-changing-places' |
      'rewind-button' |
      'moon-phase-outline' |
      'superscript-text-formatting' |
      'home' |
      'open-laptop-computer' |
      'zoom-in' |
      'music-note-black-symbol' |
      'fire-extinguisher' |
      'information-button' |
      'angle-arrow-down' |
      'edit-interface-sign' |
      'adjust-contrast' |
      'check-sign-in-a-rounded-black-square' |
      'rounded-black-square-shape' |
      'download-symbol' |
      'musical-bell-outline' |
      'youtube-logo-1' |
      'reduced-volume' |
      'sort-by-attributes' |
      'skype-logo' |
      'external-link-symbol' |
      'speech-bubbles-comment-option' |
      'long-arrow-pointing-to-the-right' |
      'font-symbol-of-letter-a' |
      'minus-sign-on-a-square-outline' |
      'chevron-pointing-to-the-left' |
      'play-sign' |
      'magic-wand' |
      'play-button' |
      'information-symbol' |
      'caret-arrow-up' |
      'crop-symbol' |
      'computer-tablet' |
      'yen-symbol' |
      'chevron-sign-down' |
      'google-plus-symbol' |
      'retweet-arrows-symbol' |
      'arrowheads-pointing-to-the-left' |
      'tumblr-logo' |
      'foursquare-button' |
      'telephone-handle-silhouette' |
      'paper-bill' |
      'white-flag-symbol' |
      'heart-shape-outline' |
      'linux-logo' |
      'increase-size-option' |
      'step-backward' |
      'list-on-window' |
      'blank-file' |
      'youtube-logo' |
      'plus-black-symbol' |
      'exchange-arrows' |
      'github-logo' |
      'bug' |
      'calendar-page-empty' |
      'sort-by-numeric-order' |
      'hard-drive' |
      'download-to-storage-drive' |
      'power-button-off' |
      'tag-black-shape' |
      'building-front' |
      'circle-shape-outline' |
      'eye-open' |
      'code' |
      'angle-pointing-to-left' |
      'facetime-button' |
      'cursor' |
      'pinterest-logo' |
      'half-star-shape' |
      'weibo-website-logo' |
      'calendar-with-spring-binder-and-date-blocks' |
      'link-symbol' |
      'magnifying-glass' |
      'dropbox-logo' |
      'sort-by-order' |
      'github-sign' |
      'add-square-button' |
      'tags' |
      'lemon' |
      'tasks-list' |
      'branch-with-leaves-black-shape' |
      'heart-shape-silhouette' |
      'share-option' |
      'x2-symbol-of-a-letter-and-a-number-subscript' |
      'upload' |
      'light-bulb' |
      'table-grid' |
      'thin-arrowheads-pointing-down' |
      'filter-tool-black-shape' |
      'music-headphones' |
      'bell-musical-tool' |
      'group-profile-users' |
      'open-folder' |
      'warning-sign-on-a-triangular-background' |
      'user-md-symbol' |
      'barcode' |
      'strikethrough' |
      'asterisk' |
      'rss-symbol' |
      'bullseye' |
      'underline-text-option' |
      'vertical-resizing-option' |
      'chevron-sign-to-right' |
      'arrow-up' |
      'hand-pointing-to-left-direction' |
      'inbox' |
      'minus-button' |
      'microphone-off' |
      'two-columns-layout' |
      'fast-forward-arrows' |
      'unlink-symbol' |
      'eject-symbol' |
      'bold-text-option' |
      'minus-sign-inside-a-black-rounded-square-shape' |
      'plane' |
      'paper-push-pin' |
      'star-half-empty' |
      'reply' |
      'android-character-symbol' |
      'refresh-page-option' |
      'paste-from-clipboard' |
      'apple-logo' |
      'flickr-website-logo-silhouette' |
      'youtube-logo-2' |
      'css-3-logo' |
      'collapse-window-option' |
      'paper-clip-outline' |
      'bull-horn-announcer' |
      'remove-button' |
      'share-post-symbol' |
      'facebook-logo-1' |
      'move-option' |
      'mobile-phone' |
      'listing-option' |
      'puzzle-piece-silhouette' |
      'arrow-pointing-right-in-a-circle' |
      'twitter-black-shape' |
      'hand-pointing-upward' |
      'italicize-text' |
      'lightning-bolt-shadow' |
      'fluffy-cloud-silhouette' |
      'umbrella-black-silhouette' |
      'left-arrow-1' |
      'up-arrow' |
      'user-shape' |
      'road-perspective' |
      'turkish-lire-symbol' |
      'padlock-unlock' |
      'flag-black-shape' |
      'list-with-dots' |
      'earth-globe' |
      'chevron-sign-left' |
      'right-arrow-in-a-circle' |
      'down-arrow' |
      'printing-tool' |
      'euro-currency-symbol' |
      'frown' |
      'sort-up' |
      'align-to-left' |
      'thumbs-up-hand-symbol' |
      'comments' |
      'arrow-down-on-black-circular-background' |
      'caret-down' |
      'cross-mark-on-a-black-circle-background' |
      'letter-p-symbol' |
      'keyboard' |
      'certificate-shape' |
      'facebook-logo' |
      'refresh-arrow' |
      'thumbs-down-silhouette' |
      'indent-right' |
      'copy-document' |
      'play-circle' |
      'dribbble-logo' |
      'minus-symbol' |
      'vk-social-network-logo' |
      'html-5-logo' |
      'signal-bars' |
      'center-text-alignment' |
      'bookmark-black-shape' |
      'four-black-squares' |
      'time' |
      'screenshot' |
      'leter-a-inside-a-black-circle' |
      'list' |
      'text-height-adjustment' |
      'terminal' |
      'cloud-storage-uploading-option';

    type iconColors = ;

    type backgroundType = 'circle' | 'rect' | 'button';

    type colorsType = Record<iconColors, string>;

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      colors: colorsType;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      colors?: colorsType;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
